export const students = {
  "CSE-A": [
    { rollNumber: "23CSEA01", name: "Aatiffa Farhana A" },
    { rollNumber: "23CSEA02", name: "Akshaya B" },
    { rollNumber: "23CSEA03", name: "Ambrein S" },
    { rollNumber: "23CSEA04", name: "Amirtha Varshini S" },
    { rollNumber: "23CSEA05", name: "Balasanthoshini M" },
    { rollNumber: "23CSEA06", name: "BAVAKARNI G" },
    { rollNumber: "23CSEA07", name: "Bharathy B" },
    { rollNumber: "23CSEA08", name: "Diloosha.B" },
    { rollNumber: "23CSEA10", name: "Hemavathi J S" },
    { rollNumber: "23CSEA11", name: "Jane Blessy Pearl Singh P" },
    { rollNumber: "23CSEA12", name: "Jeyabharathi A" },
    { rollNumber: "23CSEA13", name: "JEYACHITHRA M" },
    { rollNumber: "23CSEA14", name: "Jhanani K V" },
    { rollNumber: "23CSEA15", name: "Junia Rodha Sharan M" },
    { rollNumber: "23CSEA16", name: "Kaushika S" },
    { rollNumber: "23CSEA17", name: "Kavitha A V" },
    { rollNumber: "23CSEA18", name: "Mahalakshmi M" },
    { rollNumber: "23CSEA19", name: "Minojini G" },
    { rollNumber: "23CSEA20", name: "Nandhini K S" },
    { rollNumber: "23CSEA21", name: "Narmatha R" },
    { rollNumber: "23CSEA22", name: "Narmatha S" },
    { rollNumber: "23CSEA23", name: "Nikila K" },
    { rollNumber: "23CSEA24", name: "Rahina Shamin.H" },
    { rollNumber: "23CSEA25", name: "Ram sibe S" },
    { rollNumber: "23CSEA26", name: "Reashma M D" },
    { rollNumber: "23CSEA27", name: "SANTHIYA C" },
    { rollNumber: "23CSEA28", name: "Sathyapriya G V" },
    { rollNumber: "23CSEA29", name: "Shapna M S" },
    { rollNumber: "23CSEA30", name: "Shivani S" },
    { rollNumber: "23CSEA31", name: "Shree Dhaarshini S" },
    { rollNumber: "23CSEA32", name: "Shruthi B" },
    { rollNumber: "23CSEA33", name: "Uma Shankari V" },
    { rollNumber: "23CSEA34", name: "Varshini P" },
    { rollNumber: "23CSEA36", name: "Anto Deva J" },
    { rollNumber: "23CSEA37", name: "Balayogesh K" },
    { rollNumber: "23CSEA38", name: "DARUK RAKSHEN S" },
    { rollNumber: "23CSEA39", name: "B.DHAYA BABUJI" },
    { rollNumber: "23CSEA40", name: "Dhiraj J A L" },
    { rollNumber: "23CSEA41", name: "Giri Vaasan S S" },
    { rollNumber: "23CSEA42", name: "Gowtam O J" },
    { rollNumber: "23CSEA43", name: "Hrithick krishna .R" },
    { rollNumber: "23CSEA44", name: "Jayesh varshan p" },
    { rollNumber: "23CSEA45", name: "Jegadeesan V" },
    { rollNumber: "23CSEA46", name: "Karthi K S" },
    { rollNumber: "23CSEA47", name: "Mithun R P" },
    { rollNumber: "23CSEA48", name: "muralidhar c" },
    { rollNumber: "23CSEA49", name: "Muthukrishnan R" },
    { rollNumber: "23CSEA50", name: "Naresh kanna K" },
    { rollNumber: "23CSEA51", name: "N.Nithersan" },
    { rollNumber: "23CSEA52", name: "PRAANESHRAM R" },
    { rollNumber: "23CSEA53", name: "Prasanna Kumar M B" },
    { rollNumber: "23CSEA54", name: "Rupesh Srivathsan.S" },
    { rollNumber: "23CSEA55", name: "Santhosh M R S" },
    { rollNumber: "23CSEA56", name: "Sanjesh Kumar" },
    { rollNumber: "23CSEA57", name: "Senthil Murugan M" },
    { rollNumber: "23CSEA58", name: "Shailesh Babu S R" },
    { rollNumber: "23CSEA59", name: "Sharan V" },
    { rollNumber: "23CSEA60", name: "Sudharsan S" },
    { rollNumber: "23CSEA61", name: "Sukhail Ahamed M" },
    { rollNumber: "23CSEA62", name: "SURYA I" },
    { rollNumber: "23CSEA63", name: "YOKESH PRAVIN K B" },
    { rollNumber: "24LCSEA01", name: "Dharshan Prabhu" },
    { rollNumber: "24LCSEA02", name: "Tagore Santhosh" }
  ],
  "CSE-B": [
    { rollNumber: "23CSEB01", name: "AMRITHA B" },
    { rollNumber: "23CSEB02", name: "Anushri B" },
    { rollNumber: "23CSEB03", name: "Azhagu Meena G" },
    { rollNumber: "23CSEB04", name: "Devis Aruna Devi D" },
    { rollNumber: "23CSEB05", name: "Dhanya Johnsy AR" },
    { rollNumber: "23CSEB06", name: "Gopika Rani A M" },
    { rollNumber: "23CSEB07", name: "Harini T" },
    { rollNumber: "23CSEB08", name: "Iniya M" },
    { rollNumber: "23CSEB09", name: "Janani Kamatchi S" },
    { rollNumber: "23CSEB10", name: "JEEVAJOTHI M" },
    { rollNumber: "23CSEB11", name: "Jeyashree K A" },
    { rollNumber: "23CSEB12", name: "Kannika G" },
    { rollNumber: "23CSEB13", name: "KARISHMA S" },
    { rollNumber: "23CSEB14", name: "Kavitha M" },
    { rollNumber: "23CSEB16", name: "Keerthiga TS" },
    { rollNumber: "23CSEB17", name: "Keerthiga K" },
    { rollNumber: "23CSEB18", name: "Manasa Asvitha CK M" },
    { rollNumber: "23CSEB19", name: "Mansha T R" },
    { rollNumber: "23CSEB20", name: "Naga Harini M" },
    { rollNumber: "23CSEB21", name: "Priyadharshini M" },
    { rollNumber: "23CSEB22", name: "Rajadharshini R" },
    { rollNumber: "23CSEB23", name: "Raksana V" },
    { rollNumber: "23CSEB24", name: "Shree Vikhashini J" },
    { rollNumber: "23CSEB25", name: "Sushmitha T" },
    { rollNumber: "23CSEB26", name: "Vaishnavi S" },
    { rollNumber: "23CSEB27", name: "Vikasni T R" },
    { rollNumber: "23CSEB28", name: "Vishnu Priya T K" },
    { rollNumber: "23CSEB29", name: "Yamuna R" },
    { rollNumber: "23CSEB30", name: "Yuvasri R" },
    { rollNumber: "23CSEB31", name: "Abishek Guhan P" },
    { rollNumber: "23CSEB32", name: "Achuthan T B" },
    { rollNumber: "23CSEB33", name: "Adithya T B" },
    { rollNumber: "23CSEB34", name: "AGILESH K K" },
    { rollNumber: "23CSEB35", name: "Dakshin B" },
    { rollNumber: "23CSEB36", name: "Jayakanth S" },
    { rollNumber: "23CSEB37", name: "Karuppasamy M" },
    { rollNumber: "23CSEB38", name: "Kishore T S" },
    { rollNumber: "23CSEB39", name: "Logesh Kumar M" },
    { rollNumber: "23CSEB40", name: "Manavendra Shailesh A" },
    { rollNumber: "23CSEB41", name: "Mugesh Bala M" },
    { rollNumber: "23CSEB42", name: "Muhammad Yahyaa R" },
    { rollNumber: "23CSEB43", name: "Mutheeswaran R" },
    { rollNumber: "23CSEB44", name: "Muthunilavan D" },
    { rollNumber: "23CSEB45", name: "Nagavishnu Karthik B S" },
    { rollNumber: "23CSEB46", name: "Peniel Osborn J" },
    { rollNumber: "23CSEB48", name: "Pranav Hari TN" },
    { rollNumber: "23CSEB49", name: "Prawinkumar M" },
    { rollNumber: "23CSEB50", name: "Rohan Gandhi S" },
    { rollNumber: "23CSEB51", name: "Shanmugapriyan M" },
    { rollNumber: "23CSEB52", name: "Shiveshwar S" },
    { rollNumber: "23CSEB53", name: "Shyaam Sundar PCM" },
    { rollNumber: "23CSEB54", name: "Siva Subramami S" },
    { rollNumber: "23CSEB55", name: "Sree Krishna K N" },
    { rollNumber: "23CSEB56", name: "Suraj GV" },
    { rollNumber: "23CSEB57", name: "Surya Prakash S" },
    { rollNumber: "23CSEB58", name: "Surya S" },
    { rollNumber: "23CSEB59", name: "Vishal S" },
    { rollNumber: "23CSEB60", name: "Vishal J" },
    { rollNumber: "23CSEB61", name: "Vithesh T" },
    { rollNumber: "23CSEB62", name: "Vivash V" },
    { rollNumber: "24LCSEB01", name: "Mukesh Kanna M" },
    { rollNumber: "24LCSEB02", name: "Santhosh S" },
    { rollNumber: "24LCSEB03", name: "Santhosh Kumar D" },
    { rollNumber: "24LCSEB04", name: "Krishna Kumar N" }
  ],
  "CSE-C": [
    { rollNumber: "23CSEC01", name: "Al kabeeba A" },
    { rollNumber: "23CSEC02", name: "Alagu Gayathri L" },
    { rollNumber: "23CSEC03", name: "Aruna T" },
    { rollNumber: "23CSEC04", name: "Ashmitha G M" },
    { rollNumber: "23CSEC05", name: "Azhagu Meena M" },
    { rollNumber: "23CSEC06", name: "Deva Harsitha B V" },
    { rollNumber: "23CSEC07", name: "Girisha Malni N" },
    { rollNumber: "23CSEC08", name: "Harini L S" },
    { rollNumber: "23CSEC10", name: "Lakshetha shree J J" },
    { rollNumber: "23CSEC11", name: "Lavanya Sri K" },
    { rollNumber: "23CSEC12", name: "Loga Dharani P M" },
    { rollNumber: "23CSEC13", name: "LUCKWIN SUBINAYA R S" },
    { rollNumber: "23CSEC14", name: "Madhumitha S" },
    { rollNumber: "23CSEC15", name: "S. Madhumitha" },
    { rollNumber: "23CSEC16", name: "MATHIMITHA.B" },
    { rollNumber: "23CSEC17", name: "Prathiksha B" },
    { rollNumber: "23CSEC18", name: "Praveena T" },
    { rollNumber: "23CSEC19", name: "PREETHIKA SHREE V" },
    { rollNumber: "23CSEC20", name: "Priyanga Sri M" },
    { rollNumber: "23CSEC21", name: "Ramya J" },
    { rollNumber: "23CSEC22", name: "T. Shreyah Lakshmi" },
    { rollNumber: "23CSEC23", name: "Sujitha S S" },
    { rollNumber: "23CSEC24", name: "Swetha P" },
    { rollNumber: "23CSEC25", name: "Swetha J" },
    { rollNumber: "23CSEC26", name: "Trishamani V" },
    { rollNumber: "23CSEC27", name: "Vaishnavi K" },
    { rollNumber: "23CSEC28", name: "Vishalini S" },
    { rollNumber: "23CSEC29", name: "Yamuna B" },
    { rollNumber: "23CSEC30", name: "Yazhini B" },
    { rollNumber: "23CSEC31", name: "Ahmed Irfaan Mahdi S" },
    { rollNumber: "23CSEC32", name: "Akash S" },
    { rollNumber: "23CSEC33", name: "AMBAREESH V" },
    { rollNumber: "23CSEC35", name: "Arun S K" },
    { rollNumber: "23CSEC36", name: "Arunachalam S" },
    { rollNumber: "23CSEC37", name: "Bala SivaKumar M K" },
    { rollNumber: "23CSEC38", name: "Bharath R L" },
    { rollNumber: "23CSEC39", name: "Deepan S" },
    { rollNumber: "23CSEC40", name: "Dheenathayalan S" },
    { rollNumber: "23CSEC41", name: "Hariharan A" },
    { rollNumber: "23CSEC42", name: "Jeswin S P" },
    { rollNumber: "23CSEC43", name: "Kavin Chandran A" },
    { rollNumber: "23CSEC44", name: "Kishore M" },
    { rollNumber: "23CSEC45", name: "Krishna Kumar B K" },
    { rollNumber: "23CSEC46", name: "Manoj M" },
    { rollNumber: "23CSEC47", name: "Manojkumar M" },
    { rollNumber: "23CSEC48", name: "Mathesh Kannan T" },
    { rollNumber: "23CSEC49", name: "A K Mohamed Arshath" },
    { rollNumber: "23CSEC50", name: "Osho V" },
    { rollNumber: "23CSEC51", name: "Raamkumar M" },
    { rollNumber: "23CSEC52", name: "Rahul R R" },
    { rollNumber: "23CSEC53", name: "Rajesh Kumar D" },
    { rollNumber: "23CSEC54", name: "Rohit" },
    { rollNumber: "23CSEC55", name: "Sachin Bala B" },
    { rollNumber: "23CSEC56", name: "Sarankumar R" },
    { rollNumber: "23CSEC57", name: "Siddhaarth P S" },
    { rollNumber: "23CSEC58", name: "Sri Balaji M" },
    { rollNumber: "23CSEC59", name: "Syed Ameen G" },
    { rollNumber: "23CSEC60", name: "THARUN R" },
    { rollNumber: "23CSEC61", name: "Veer Sehwag L K" },
    { rollNumber: "23CSEC62", name: "VIJAY VINDHAN M" },
    { rollNumber: "23CSEC63", name: "Vishwajit M" },
    { rollNumber: "24LCSEC01", name: "Prakash L G" }
  ]
};
  
  export const staffCredentials = {
    IICSEA: { password: "csea111", incharge: "Mrs. K. Shantha Sheela", section: "CSE-A" },
    IICSEB: { password: "cseb222", incharge: "Mr. G. Balamuralikrishnan", section: "CSE-B" },
    IICSEC: { password: "csec333", incharge: "Mrs. R. Niranjana", section: "CSE-C" },
  };
  
  export const validateStaffLogin = (username, password) => {
    const staff = staffCredentials[username];
    return staff && staff.password === password ? staff : null;
  };
  